#aviationstackapi
AVIATIONSTACK_API_KEY = "1f868d24efecaa047495616b06569807"

#azure connection string
connection_string = "DefaultEndpointsProtocol=https;AccountName=aviationstorage1;AccountKey=3fvJoehB4iVZ0KwEUjmH6XiL10uvA64Lod547QtOiRNQM0+9W7HiNYL2oGIarHkwSQwhMzqz54lr+AStfVkfew==;EndpointSuffix=core.windows.net"